In [16]:
import pandas as pd

from surprise import Dataset, Reader
from surprise import SVD, NMF
from surprise.model_selection import cross_validate, train_test_split, GridSearchCV

### Load data

In [9]:
df = pd.read_csv("data/ratings_beauty.csv")

reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(df[['UserId', 'ProductId', 'Rating']], reader)

In [12]:
print('Number of ratings: %d\nNumber of ProductIds: %d\nNumber of users: %d' % (len(df), len(df['Rating'].unique()), len(df['UserId'].unique())))

Number of ratings: 2023070
Number of ProductIds: 5
Number of users: 1210271

## Apply SVD

In [24]:
trainset, testset = train_test_split(data, test_size=0.2)

model = SVD(n_factors=80, n_epochs=20, lr_all=0.005, reg_all=0.2)
model.fit(trainset)
predictions = model.test(testset)

In [21]:
df.head(5)

           UserId   ProductId  Rating   Timestamp
0  A39HTATAQ9V7YF  0205616461     5.0  1369699200
1  A3JM6GV9MNOF9X  0558925278     3.0  1355443200
2  A1Z513UWSAAO0F  0558925278     5.0  1404691200
3  A1WMRR494NWEWV  0733001998     4.0  1382572800
4  A3IAAVS479H7M7  0737104473     1.0  1274227200

In [25]:
df[df['UserId'] == 'A39HTATAQ9V7YF']

                 UserId   ProductId  Rating   Timestamp
0        A39HTATAQ9V7YF  0205616461     5.0  1369699200
899125   A39HTATAQ9V7YF  B002OVV7F0     3.0  1369699200
969482   A39HTATAQ9V7YF  B0031IH5FQ     5.0  1369699200
1499680  A39HTATAQ9V7YF  B006GQPZ8E     4.0  1369699200

In [26]:
model.predict('A39HTATAQ9V7YF', '0205616461' )

Prediction(uid='A39HTATAQ9V7YF', iid='0205616461', r_ui=None, est=np.float64(4.110788947863889), details={'was_impossible': False})

In [27]:
predictions

[Prediction(uid='A2UO9JXYQ1V2LZ', iid='B0095JFUCK', r_ui=3.0, est=np.float64(4.130292746386228), details={'was_impossible': False}),
 Prediction(uid='A2O623ZM6B79Y2', iid='B007FKBW64', r_ui=3.0, est=np.float64(3.947999980549924), details={'was_impossible': False}),
 Prediction(uid='A3C3I4LLSM9ZZM', iid='B009HULFLW', r_ui=5.0, est=np.float64(3.5221044451362298), details={'was_impossible': False}),
 Prediction(uid='A1EQRMRJWUWIR', iid='B004AGF8ZW', r_ui=5.0, est=np.float64(4.148627457280272), details={'was_impossible': False}),
 Prediction(uid='A2UV6IF4BRWABU', iid='B003PZAO7Q', r_ui=5.0, est=np.float64(3.910458368279117), details={'was_impossible': False}),
 Prediction(uid='ADCVT82H6UHNG', iid='B0002GP9YO', r_ui=1.0, est=np.float64(3.4984936302099925), details={'was_impossible': False}),
 Prediction(uid='A1G3CK12TKTXRA', iid='B000YJ2SKM', r_ui=5.0, est=np.float64(4.33911066436365), details={'was_impossible': False}),
 Prediction(uid='AB5COI15LTH9', iid='B002QXQ72E', r_ui=5.0, est=np.float64(4.287052954394291), details={'was_impossible': False}),
 Prediction(uid='A3091RP0SPZLMN', iid='B002YLJJ1O', r_ui=5.0, est=np.float64(3.7509487646836543), details={'was_impossible': False}),
 Prediction(uid='A3HRUMD0ZDBANU', iid='B000RO6ZDA', r_ui=2.0, est=np.float64(4.19883540283911), details={'was_impossible': False}),
 Prediction(uid='A2RYT8O7T5NPYT', iid='B001CB5OE8', r_ui=5.0, est=np.float64(4.375358267412324), details={'was_impossible': False}),
 Prediction(uid='A3O7SWYO6LU350', iid='B001AO0WCG', r_ui=5.0, est=np.float64(4.468184290673327), details={'was_impossible': False}),
 Prediction(uid='A3CDIC6IPDKNU1', iid='B003BOKL0G', r_ui=1.0, est=np.float64(3.6232320894275456), details={'was_impossible': False}),
 Prediction(uid='A1AC12Z9PA2QS9', iid='B00BS1SP2U', r_ui=5.0, est=np.float64(4.2341600092587415), details={'was_impossible': False}),
 Prediction(uid='A1KT19TDP9VE63', iid='B001N444JK', r_ui=4.0, est=np.float64(4.8545176179052865), details={'was_impossible': False}),
 Prediction(uid='AFIS5X5CNUQLK', iid='B0002Z8YR4', r_ui=5.0, est=np.float64(4.220287082806185), details={'was_impossible': False}),
 Prediction(uid='AH71KRURD5VYT', iid='B001H9657K', r_ui=2.0, est=np.float64(3.9876259220669033), details={'was_impossible': False}),
 Prediction(uid='A19WEEGB05YAZ3', iid='B00HM6IVXI', r_ui=3.0, est=np.float64(3.351324536779923), details={'was_impossible': False}),
 Prediction(uid='AB0VX6D37FZWT', iid='B00014EKJC', r_ui=5.0, est=np.float64(4.264457853681137), details={'was_impossible': False}),
 Prediction(uid='AZZED49ZFAMWU', iid='B0011UR1H8', r_ui=5.0, est=np.float64(4.313603224446344), details={'was_impossible': False}),
 Prediction(uid='A2JM844PF4GWZO', iid='B004GQZX4M', r_ui=2.0, est=np.float64(3.946091871645941), details={'was_impossible': False}),
 Prediction(uid='A10RXZ007K0XYS', iid='B004I5H8PS', r_ui=2.0, est=np.float64(4.322447316246424), details={'was_impossible': False}),
 Prediction(uid='A1XHHRPCKMDU5V', iid='B001U1HI5I', r_ui=4.0, est=np.float64(3.5857961206730393), details={'was_impossible': False}),
 Prediction(uid='AJFYTSR7MN6O2', iid='B000O5162M', r_ui=5.0, est=np.float64(4.7165282091487155), details={'was_impossible': False}),
 Prediction(uid='A1PBM4M1XMK8XU', iid='B00D8XAT9S', r_ui=2.0, est=np.float64(3.695714485470973), details={'was_impossible': False}),
 Prediction(uid='A339O263MZ9BQ4', iid='B000GHWSG6', r_ui=5.0, est=np.float64(4.367005122294316), details={'was_impossible': False}),
 Prediction(uid='A144QXJNAVYY2C', iid='B004DOYM2Q', r_ui=5.0, est=np.float64(3.7886905324914113), details={'was_impossible': False}),
 Prediction(uid='A1KRU656ZF90MW', iid='B0010EBGS0', r_ui=4.0, est=np.float64(4.453808815023671), details={'was_impossible': False}),
 Prediction(uid='A26NI8NU05WJQ4', iid='B007KHBFYG', r_ui=5.0, est=np.float64(4.224481678955693), details={'was_impossible': False}),
 Prediction(uid='A194XYQR0NNEQ6', iid='B00011QTRQ', r_ui=5.0, est=np.float64(4.148627457280272), details={'was_impossible': False}),
 Prediction(uid='A23MCO4TJSHQU4', iid='B00BCYX8LG', r_ui=5.0, est=np.float64(3.969693107962692), details={'was_impossible': False}),
 Prediction(uid='A3A17DITARMCUQ', iid='B002RC184Q', r_ui=5.0, est=np.float64(4.284474228798712), details={'was_impossible': False}),
 Prediction(uid='A2HUSM974TN6K0', iid='B0065LOG6M', r_ui=5.0, est=np.float64(4.256590971155187), details={'was_impossible': False}),
 Prediction(uid='A1SPUHGJT9QGKE', iid='B00F8KT45Y', r_ui=4.0, est=np.float64(4.3256781182878585), details={'was_impossible': False}),
 Prediction(uid='A3EM5N8WENP1MZ', iid='B00BT1TFIW', r_ui=4.0, est=np.float64(3.81699394307233), details={'was_impossible': False}),
 Prediction(uid='A1SFAAU1VIPWDC', iid='B0012LIHUG', r_ui=5.0, est=np.float64(4.2441738819115065), details={'was_impossible': False}),
 Prediction(uid='A1NSBTWZ1UPXKI', iid='B0052GADTK', r_ui=3.0, est=np.float64(4.10625042858167), details={'was_impossible': False}),
 Prediction(uid='A1YZ6IHGQZBR91', iid='B004TWCIK0', r_ui=4.0, est=np.float64(3.111895100580492), details={'was_impossible': False}),
 Prediction(uid='A1YHXGV6GC51IM', iid='B004CQ710U', r_ui=5.0, est=np.float64(4.17021737837007), details={'was_impossible': False}),
 Prediction(uid='A2BV75WIB0IWJK', iid='B00154MOEU', r_ui=5.0, est=np.float64(4.15686861410494), details={'was_impossible': False}),
 Prediction(uid='A1FIR3SDQDJR9D', iid='B00DOQ25QE', r_ui=5.0, est=np.float64(4.4932528135510745), details={'was_impossible': False}),
 Prediction(uid='A34WL2C8HPQ23W', iid='B005JFW1HQ', r_ui=5.0, est=np.float64(4.585180814415747), details={'was_impossible': False}),
 Prediction(uid='A1UZUOBA4B1PYK', iid='B000G666HE', r_ui=5.0, est=np.float64(4.662125706510586), details={'was_impossible': False}),
 Prediction(uid='A3RE1QXOMWNFF9', iid='B001KYVPGI', r_ui=5.0, est=np.float64(4.571228632404048), details={'was_impossible': False}),
 Prediction(uid='A3EVC62JMOHETW', iid='B000AUG5V8', r_ui=4.0, est=np.float64(4.0189998840666625), details={'was_impossible': False}),
 Prediction(uid='A23QSGR1I6OJLF', iid='B006WVCF18', r_ui=3.0, est=np.float64(3.606928025661606), details={'was_impossible': False}),
 Prediction(uid='A1JS5UAGEI59NA', iid='B0009OAHQO', r_ui=1.0, est=np.float64(4.107094767043718), details={'was_impossible': False}),
 Prediction(uid='A3BVR102ZF87U0', iid='B00IIWVJ2U', r_ui=4.0, est=np.float64(4.3665031721549905), details={'was_impossible': False}),
 Prediction(uid='A3PFHQTLUBZEPR', iid='B000O3UCTC', r_ui=5.0, est=np.float64(3.896463055604925), details={'was_impossible': False}),
 Prediction(uid='A14Z6VY9EIWOFF', iid='B0028TV2DA', r_ui=4.0, est=np.float64(4.107795539786737), details={'was_impossible': False}),
 Prediction(uid='A3HLI2ZKGOH3MZ', iid='B00AATKKN8', r_ui=2.0, est=np.float64(3.4063474654306276), details={'was_impossible': False}),
 Prediction(uid='A1BJH6IJKPJ4X', iid='B00476GC0U', r_ui=4.0, est=np.float64(4.1385009205617775), details={'was_impossible': False}),
 Prediction(uid='A2NIIB3VA49IG0', iid='B003V265QW', r_ui=4.0, est=np.float64(3.9662917600560696), details={'was_impossible': False}),
 Prediction(uid='A1YPM4GCO8I1W1', iid='B0083ZLXFU', r_ui=5.0, est=np.float64(4.548303478792594), details={'was_impossible': False}),
 Prediction(uid='A78B0IBG47Y2U', iid='B0027SU58A', r_ui=1.0, est=np.float64(4.078266844230776), details={'was_impossible': False}),
 Prediction(uid='A6D9HLUU47HYE', iid='B004GYUJ02', r_ui=5.0, est=np.float64(4.148627457280272), details={'was_impossible': False}),
 Prediction(uid='A307METH5B8MTD', iid='B004NMF63W', r_ui=4.0, est=np.float64(3.7353917033919477), details={'was_impossible': False}),
 Prediction(uid='A3MN7EOK0TPJ9T', iid='B00A7W13Q6', r_ui=5.0, est=np.float64(4.308729130303383), details={'was_impossible': False}),
 Prediction(uid='A2Y0KXP1FSBZAC', iid='B000C1Z1PG', r_ui=5.0, est=np.float64(4.21567952899826), details={'was_impossible': False}),
 Prediction(uid='A2VMK08LGKI3JT', iid='B007VIIK9W', r_ui=5.0, est=np.float64(4.5370327005066535), details={'was_impossible': False}),
 Prediction(uid='A1QROWPKLXAP46', iid='B007HQYHQ8', r_ui=5.0, est=np.float64(3.940767580258506), details={'was_impossible': False}),
 Prediction(uid='A8NCC3UY8VKEY', iid='B00017X8PQ', r_ui=5.0, est=np.float64(4.3905187585316785), details={'was_impossible': False}),
 Prediction(uid='A2WJ7708VN0ZW2', iid='B0044EFEHM', r_ui=3.0, est=np.float64(3.974026094976144), details={'was_impossible': False}),
 Prediction(uid='A1CULLV7J99TGL', iid='B0012QD7EC', r_ui=1.0, est=np.float64(3.8196540966194075), details={'was_impossible': False}),
 Prediction(uid='A1GPAKJ3YMCFDL', iid='B002WR58XS', r_ui=5.0, est=np.float64(4.162090820404369), details={'was_impossible': False}),
 Prediction(uid='AX29GJR026OH0', iid='B0038T47IG', r_ui=5.0, est=np.float64(4.148627457280272), details={'was_impossible': False}),
 Prediction(uid='A3NVFJ49O4GMRC', iid='B001D0NARQ', r_ui=5.0, est=np.float64(4.634557470168118), details={'was_impossible': False}),
 Prediction(uid='A36PLPT0SBMAMM', iid='B00121UVU0', r_ui=4.0, est=np.float64(4.417760426150439), details={'was_impossible': False}),
 Prediction(uid='A277OQN19GHDD1', iid='B0044MROAE', r_ui=5.0, est=np.float64(4.191989159026992), details={'was_impossible': False}),
 Prediction(uid='AU9WCTX0766FY', iid='B000XE0D00', r_ui=5.0, est=np.float64(4.387520992202225), details={'was_impossible': False}),
 Prediction(uid='A2N74HADTQWVRK', iid='B003B6S36S', r_ui=5.0, est=np.float64(4.365668657432853), details={'was_impossible': False}),
 Prediction(uid='AE4RCEWWJ7ALY', iid='B000B9P4R4', r_ui=2.0, est=np.float64(4.2955008144375615), details={'was_impossible': False}),
 Prediction(uid='A2PBNLW7L2M761', iid='B001DYM62C', r_ui=5.0, est=np.float64(4.389953772846555), details={'was_impossible': False}),
 Prediction(uid='AGGJO1G7SHCUU', iid='B00FG4F5P0', r_ui=5.0, est=np.float64(4.029419623260038), details={'was_impossible': False}),
 Prediction(uid='A2RZ4Z4OB1X3RX', iid='B000JL1MP2', r_ui=5.0, est=np.float64(4.1117077902167605), details={'was_impossible': False}),
 Prediction(uid='A130CS9TZXPVCC', iid='B00FRDPNA2', r_ui=5.0, est=np.float64(4.4825608763237925), details={'was_impossible': False}),
 Prediction(uid='A1VT71NMEB53L4', iid='B002RDBL7Y', r_ui=5.0, est=np.float64(4.494342215800369), details={'was_impossible': False}),
 Prediction(uid='A3CRA7EPM4EI2Z', iid='B007RTR8UM', r_ui=5.0, est=np.float64(3.936458734459162), details={'was_impossible': False}),
 Prediction(uid='A3C4O11IC6O97', iid='B00HAYBLTS', r_ui=2.0, est=np.float64(4.224278190090764), details={'was_impossible': False}),
 Prediction(uid='A2VSL9FGZQX6GV', iid='B003GMVD96', r_ui=5.0, est=np.float64(3.9206007507196716), details={'was_impossible': False}),
 Prediction(uid='A452CT3MSSE98', iid='B000142JDG', r_ui=5.0, est=np.float64(4.26805740669584), details={'was_impossible': False}),
 Prediction(uid='A1GWY3VJ0V4ZL5', iid='B00181OKDI', r_ui=2.0, est=np.float64(3.962555360450286), details={'was_impossible': False}),
 Prediction(uid='AFS12MCX0TJI7', iid='B001H9289Y', r_ui=3.0, est=np.float64(4.398490788715266), details={'was_impossible': False}),
 Prediction(uid='A2IVG56DFTO5ML', iid='B0056KD6N2', r_ui=5.0, est=np.float64(4.570130084830132), details={'was_impossible': False}),
 Prediction(uid='A669IZJ5BHD2G', iid='B004LIG6SC', r_ui=5.0, est=np.float64(4.664762137409568), details={'was_impossible': False}),
 Prediction(uid='A278PW86DVNJSQ', iid='B0030HMQTS', r_ui=5.0, est=np.float64(4.4089332679359785), details={'was_impossible': False}),
 Prediction(uid='A130VKD6760TV5', iid='B008LDFU26', r_ui=1.0, est=np.float64(3.0820271917770277), details={'was_impossible': False}),
 Prediction(uid='A2JAYC08WE7N01', iid='B004KS2LYQ', r_ui=5.0, est=np.float64(4.320507612396711), details={'was_impossible': False}),
 Prediction(uid='A2YWBRTOIX6P6S', iid='B003AODMSA', r_ui=3.0, est=np.float64(4.065234173108517), details={'was_impossible': False}),
 Prediction(uid='A34WJQ3ATLZ2M4', iid='B0002YFQ6W', r_ui=5.0, est=np.float64(4.48740952926123), details={'was_impossible': False}),
 Prediction(uid='A1R36UI69TDM9T', iid='B000052Y31', r_ui=5.0, est=np.float64(4.167773039861994), details={'was_impossible': False}),
 Prediction(uid='A1W7TX5CIQ1U6I', iid='B00C9LK66G', r_ui=2.0, est=np.float64(3.86958662600408), details={'was_impossible': False}),
 Prediction(uid='A1IYAJUX69GIC6', iid='B009JDDJLG', r_ui=5.0, est=np.float64(3.6631156589203324), details={'was_impossible': False}),
 Prediction(uid='A2HNR418LK01KH', iid='B000PY17PI', r_ui=3.0, est=np.float64(4.0460164283337665), details={'was_impossible': False}),
 Prediction(uid='A9QZBUCV1F1N3', iid='B00BY0938K', r_ui=3.0, est=np.float64(4.208615550491234), details={'was_impossible': False}),
 Prediction(uid='AK152DDQVMYA8', iid='B000JQLNO2', r_ui=5.0, est=np.float64(4.202362970497222), details={'was_impossible': False}),
 Prediction(uid='A1JLDAVYU061XH', iid='B0009DVMAU', r_ui=5.0, est=np.float64(3.2888543907997176), details={'was_impossible': False}),
 Prediction(uid='A3MFFPMCGZG7OA', iid='B004O3TZUK', r_ui=1.0, est=np.float64(4.160693388389907), details={'was_impossible': False}),
 Prediction(uid='A2J9JFHEKKQIRO', iid='B002L890GE', r_ui=5.0, est=np.float64(4.375133053954228), details={'was_impossible': False}),
 Prediction(uid='A1N3OYLJ7BNR3Q', iid='B000V33OGS', r_ui=5.0, est=np.float64(3.9731860673901505), details={'was_impossible': False}),
 Prediction(uid='AHZVZVWIK0911', iid='B000TD5KR6', r_ui=5.0, est=np.float64(3.7759791728379373), details={'was_impossible': False}),
 Prediction(uid='A2974B17DKU2UH', iid='B002T5AS8S', r_ui=5.0, est=np.float64(4.254678855422415), details={'was_impossible': False}),
 Prediction(uid='APJDV8NQFQ7D0', iid='B00E8X79V8', r_ui=5.0, est=np.float64(4.366878896552848), details={'was_impossible': False}),
 Prediction(uid='A2A3HDTYWQSXXV', iid='B001AWG0BK', r_ui=4.0, est=np.float64(4.500751146476775), details={'was_impossible': False}),
 Prediction(uid='AIPSUF99BQ17T', iid='B00152S946', r_ui=3.0, est=np.float64(4.045803233853544), details={'was_impossible': False}),
 Prediction(uid='A2BYKKBTK0XKF2', iid='B000CLL2HM', r_ui=5.0, est=np.float64(4.238425115769877), details={'was_impossible': False}),
 Prediction(uid='ANPZR5PU3N8BQ', iid='B009DU4QYE', r_ui=2.0, est=np.float64(4.1590045621778255), details={'was_impossible': False}),
 Prediction(uid='A22O0RUQOCBWQX', iid='B000C1UDPO', r_ui=4.0, est=np.float64(4.191657845027403), details={'was_impossible': False}),
 Prediction(uid='A126F7OK2T4JUX', iid='B004Y9LZU2', r_ui=2.0, est=np.float64(4.222684089686121), details={'was_impossible': False}),
 Prediction(uid='A33J2VWP9HXDU9', iid='B00I6CRX04', r_ui=4.0, est=np.float64(4.131145829759894), details={'was_impossible': False}),
 Prediction(uid='A1J5H2X31XNG4D', iid='B0018ZPZJC', r_ui=4.0, est=np.float64(4.148635564907697), details={'was_impossible': False}),
 Prediction(uid='A3SJ3BA9ENV7GE', iid='B00BIAKTMU', r_ui=5.0, est=np.float64(4.43629574540222), details={'was_impossible': False}),
 Prediction(uid='A2UPGJCKAYZOLV', iid='B00C6NR0M0', r_ui=5.0, est=np.float64(4.4782142243260825), details={'was_impossible': False}),
 Prediction(uid='A2SR8ZPX7G1YY5', iid='B002ULA304', r_ui=4.0, est=np.float64(4.433588708254024), details={'was_impossible': False}),
 Prediction(uid='A3V6IGD5A8ZU94', iid='B004QNIC1G', r_ui=5.0, est=np.float64(4.475768181643596), details={'was_impossible': False}),
 Prediction(uid='A2REWDVBGRFUCH', iid='B0009R1526', r_ui=1.0, est=np.float64(4.0248210797655135), details={'was_impossible': False}),
 Prediction(uid='A1F9UT23TUX976', iid='B0035LCWB6', r_ui=4.0, est=np.float64(4.056647449549386), details={'was_impossible': False}),
 Prediction(uid='A2BV5GFA7DF66C', iid='B004D24818', r_ui=5.0, est=np.float64(3.8530484948594355), details={'was_impossible': False}),
 Prediction(uid='A1GFIGKT43Z4HG', iid='B003F7497K', r_ui=5.0, est=np.float64(3.8106607513129904), details={'was_impossible': False}),
 Prediction(uid='A30A95IG9RSTLO', iid='B00D9NV20C', r_ui=5.0, est=np.float64(4.653033245463366), details={'was_impossible': False}),
 Prediction(uid='A1VZV11SXWQBX7', iid='B000CONLRI', r_ui=5.0, est=np.float64(3.7083466125155122), details={'was_impossible': False}),
 Prediction(uid='A1VUSLNGDCIOVP', iid='B00014DZ2K', r_ui=5.0, est=np.float64(4.549750505208465), details={'was_impossible': False}),
 Prediction(uid='A34CQL47I9A4CY', iid='B000VRCSWU', r_ui=4.0, est=np.float64(4.148627457280272), details={'was_impossible': False}),
 Prediction(uid='A190EAFTGCQNED', iid='B003V21WO2', r_ui=5.0, est=np.float64(4.176478834825769), details={'was_impossible': False}),
 Prediction(uid='A5XADVKUUIU5M', iid='B002IF1WOS', r_ui=5.0, est=np.float64(4.399455861383281), details={'was_impossible': False}),
 Prediction(uid='A3LOGCH1G4F6RW', iid='B00JJUHNNY', r_ui=2.0, est=np.float64(3.887146100608809), details={'was_impossible': False}),
 Prediction(uid='A39MCNVF5MWLL6', iid='B004350JKY', r_ui=1.0, est=np.float64(3.473401941649632), details={'was_impossible': False}),
 Prediction(uid='A37I5PRTUM7KC0', iid='B004Z0SHBK', r_ui=4.0, est=np.float64(3.368306834814562), details={'was_impossible': False}),
 Prediction(uid='A3M12RFAVHZXQS', iid='B002ZOU4SW', r_ui=4.0, est=np.float64(4.131879201116047), details={'was_impossible': False}),
 Prediction(uid='A39BPISKTLE3MJ', iid='B00K5B25KM', r_ui=5.0, est=np.float64(4.635227955475039), details={'was_impossible': False}),
 Prediction(uid='A351804L86H9Z6', iid='B00B59ATRY', r_ui=5.0, est=np.float64(4.237975509821283), details={'was_impossible': False}),
 Prediction(uid='A2X9LISU3HLM0R', iid='B000NPWQWM', r_ui=5.0, est=np.float64(4.268611806258882), details={'was_impossible': False}),
 Prediction(uid='A1MC79DHSIREH3', iid='B004WPGIR8', r_ui=2.0, est=np.float64(4.221986011367727), details={'was_impossible': False}),
 Prediction(uid='A3SGLVR09WCPP6', iid='B00143UYPS', r_ui=1.0, est=np.float64(3.390651800288694), details={'was_impossible': False}),
 Prediction(uid='A2J2NGMYTXHOVH', iid='B000C21BK4', r_ui=5.0, est=np.float64(4.226315404125107), details={'was_impossible': False}),
 Prediction(uid='A2GGQUU05A61UN', iid='B002UKJN0G', r_ui=5.0, est=np.float64(3.8265063809192688), details={'was_impossible': False}),
 Prediction(uid='A1L5RC4SGL9W0R', iid='B004BCT93C', r_ui=5.0, est=np.float64(4.098237261817826), details={'was_impossible': False}),
 Prediction(uid='A210O6L9KCLNB6', iid='B000ZMBSPE', r_ui=5.0, est=np.float64(4.346573948854441), details={'was_impossible': False}),
 Prediction(uid='A1OH2YRMQ8UPDZ', iid='B004WSXD4G', r_ui=5.0, est=np.float64(3.879316967623436), details={'was_impossible': False}),
 Prediction(uid='ATSXHFPFZ4MAV', iid='B005MTK4RI', r_ui=3.0, est=np.float64(4.767032369057334), details={'was_impossible': False}),
 Prediction(uid='A25WU13I1PQFGQ', iid='B000GZ7GH4', r_ui=5.0, est=np.float64(4.092120370317586), details={'was_impossible': False}),
 Prediction(uid='ASCFOP5CHEB8V', iid='B000PHP86E', r_ui=5.0, est=np.float64(4.341087072638951), details={'was_impossible': False}),
 Prediction(uid='A3JOVU33I2LUFJ', iid='B00AXXHCLY', r_ui=5.0, est=np.float64(4.556732615231319), details={'was_impossible': False}),
 Prediction(uid='A3EEPD5VCPVJJ8', iid='B0050IJBDO', r_ui=2.0, est=np.float64(4.1296667396885445), details={'was_impossible': False}),
 Prediction(uid='A8WWKAFU0Y85Q', iid='B000RO0ON2', r_ui=5.0, est=np.float64(4.231555343112534), details={'was_impossible': False}),
 Prediction(uid='A3LKW75G9Z0H4D', iid='B00C61F1C8', r_ui=3.0, est=np.float64(3.8581726421351203), details={'was_impossible': False}),
 Prediction(uid='A3G09OEUNOL233', iid='B00380VC0Q', r_ui=5.0, est=np.float64(4.382817403998904), details={'was_impossible': False}),
 Prediction(uid='A1AOKMH8O1HQMN', iid='B003J48F3I', r_ui=5.0, est=np.float64(4.374917104283279), details={'was_impossible': False}),
 Prediction(uid='A2MWCRY6KL7TSV', iid='B0017R9K7Y', r_ui=5.0, est=np.float64(3.6622096659826355), details={'was_impossible': False}),
 Prediction(uid='A5WKE9JXFN460', iid='B0046KG8DS', r_ui=5.0, est=np.float64(4.05337811350059), details={'was_impossible': False}),